name: docs
description: Documentation for El Darto
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  static_shock: ^0.0.14

dev_dependencies:
  lints: ^6.0.0
  test: ^1.21.0
