name: Test deployment

on:
  pull_request:
    branches:
      - master
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get
      - name: Test build website
        run: dart pub run shock build

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build